apply/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('apply', views.apply, name='apply'),
    path('showall/', views.show_all_apply, name='showall'),    
]

urlpatterns += [
    path('myapply/', views.myapply, name='my-apply'),
    path('welcome/', views.welcome, name='welcome'),
]

urlpatterns += [
    path('updateapply/<int:id>', views.update_apply),
]

urlpatterns += [
    path('north/', views.north, name='north'),
    path('mid/', views.mid, name='mid'),
    path('south/', views.south, name='south'),
    path('east/', views.east, name='east'),
]

bonus/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('how/', views.how, name='how'),    
    path('prizes/', views.PrizeListView.as_view()),
    path('prizes/<int:pk>', views.PrizeDetailView.as_view(), name='prize-detail'),
]

urlpatterns += [
    path('create/', views.create, name='create'),
    path('comment/', views.comment, name='comment'),
]

vh5000/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.views.generic import RedirectView 
urlpatterns = [
    path('', RedirectView.as_view(url='/apply/welcome', permanent=True)),
    path('admin/', admin.site.urls),
    path('apply/', include('apply.urls')),
    path('bonus/', include('bonus.urls')),
    path('store/', include('bonus.urls')),
]

# for loading static files
from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.STATIC_URL)

# for loading media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

apply/models.py
from django.db import models
from django.contrib.auth.models import User     # new

# Create your models here.
class Person(models.Model):

    VOUCHER_CHOICES = [
        ('PP', '紙本'),
        ('CC', '信用卡'),
        ('ET', '電子票劵'),
        ('MB', '行動支付')
    ]
    ssn = models.CharField(max_length=10, blank=False)
    tel = models.CharField(max_length=20, blank=False)
    voucher_id = models.CharField(max_length=2, choices = VOUCHER_CHOICES, default='PP')
    account = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True) # new

    class Meta:
        ordering = ['-ssn']

    def __str__(self):
        return self.ssn + ", " + str(self.account)

apply/forms.py
from django import forms
from .models import Person
from django.core.exceptions import ValidationError

class PersonModelForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ['ssn', 'tel', 'voucher_id'] 

        # widget 用來設定介面的呈現
        widgets = {
            'ssn': forms.TextInput(attrs = {'class': 'form-control'}),
            'tel': forms.TextInput(attrs = {'class': 'form-control'}),
            'voucher_id': forms.RadioSelect()
            # 'voucher_id': forms.Select(attrs = {'class': 'form-control'}),
        }

        labels = {
            'ssn': '身分證字號',
            'tel': '電話號碼',
            'voucher_id': '綁定'
        }

    # override the clean_<fieldname>() method
    # 身分證必須剛好 10 個字
    def clean_ssn(self):
        data = self.cleaned_data['ssn'] # 通過基本檢查乾淨資料

        if len(data) != 10 :
            raise ValidationError('身分證長度必須為 10')

        # Remember to always return the cleaned data.
        return data

    # 電話號碼必須大於五個字
    def clean_tel(self):
        data = self.cleaned_data['tel']

        if len(data) < 5 :
            raise ValidationError('電話長度不可小於5')

        # Remember to always return the cleaned data.
        return data        

apply/views.py
from django.contrib.auth import login
from django.shortcuts import render
from .models import Person
from .forms import PersonModelForm
from django.http import HttpResponse
from django.shortcuts import redirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def welcome(request):
    if request.user.is_authenticated:
        # return redirect("/apply/myapply")
        return render(request, "apply/welcome.html")
    else:    
        return render(request, "apply/welcome.html")

# you can apply only when you have login
'''
if POST
    if applied person
       f = form(POST, applied person)   # update
       save if valid; show fail if invalid
    else                                # create new
       f = form(POST)
       save if valid; show fail if invalid
else (GET)
    if applied person
       f = form(applied person)
       go to apply
    else
       f = new form
       go to apply
'''
@login_required
def apply(request):
    if request.method == "POST":
        applied_person = Person.objects.filter(account = request.user)
        if applied_person: 
            update_person = applied_person[0]
            form = PersonModelForm(request.POST, instance = update_person)
            if form.is_valid():
                form.save()
                return render(request, "apply/apply_success.html", {'form': form}) 
            else: 
                return render(request, "apply/apply_fail.html", {'form': form}) 
        else:
            form = PersonModelForm(request.POST)
            if form.is_valid():
                model_instance = form.save(commit=False)
                model_instance.account = request.user
                model_instance.save()
                return render(request, "apply/apply_success.html", {'form': form}) 
            else:
                return render(request, "apply/apply_fail.html", {'form': form}) 
    
    # GET
    applied_person = Person.objects.filter(account = request.user)
    if applied_person: 
        form = PersonModelForm(instance = applied_person[0])
    else:
        form = PersonModelForm()

    return render(request, "apply/apply.html", {'form': form})

# show my application data based on the login account
@login_required
def myapply(request):
    context = {}
    if request.user.is_authenticated:
        # get the person
        person = Person.objects.filter(account=request.user)
        if person:
            context = {
                "user": request.user,
                "person": person[0]
            }
        return render(request, "apply/my_apply.html", context)
    else:
        return redirect("/accounts/login")           


# show application for all persons
def show_all_apply(request):
    person_list = Person.objects.all()
    context = {
        'person_list': person_list
    }
    return render(request, "apply/show_all.html", context)

from django.shortcuts import get_object_or_404

# update the data based on the person's primay key
def update_apply(request, id):
    obj = get_object_or_404(Person, id = id)
    # obj = Person.objects.get(id = id)
    form = PersonModelForm(request.POST or None, instance = obj)

    print (">> form.is_bound: ", form.is_bound)
    print (">> form.is_valid(): ", form.is_valid())
    print (">> When form is not bound, it is not valid")
    if form.is_valid():
        form.save()
        return render(request, "apply/update_success.html")
 
    context = {'form':form} 
 
    return render(request, "apply/update_apply.html", context)


def north(request):
        return render(request, "apply/north.html")

def mid(request):
        return render(request, "apply/mid.html")

def south(request):
        return render(request, "apply/south.html")

def east(request):
        return render(request, "apply/east.html")

apply/templates/apply/apply.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="form-group col-md-6">

                {{ form.as_p }}

                <input class="btn btn-success" type="submit" value="提交" />
            </div>
        </div>
    </form>

{% endblock %}

apply/templates/apply/apply_fail.html
{% extends "base.html" %}

{% block content %}

<p>資料輸入錯誤</p>

{{ form.errors }}

{% endblock %}

apply/templates/apply/apply_success.html
{% extends "base.html" %}

{% block content %}

<p>綁定成功</p>

<ul>
   <li> {{form.ssn.label}}: {{form.ssn.value}}
   <li> {{form.tel.label}}: {{form.tel.value}}
   <li> {{form.voucher_id.label}}: {{form.voucher_id.value}} 
</ul>   

{% endblock %}

apply/templates/apply/east.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-sm-6 col-md-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCHuxVgy76DTMdWsQLnIu09eZAFs06zGj9tA&usqp=CAU" alt="" width="260px" class="img-fluid">
        <h3 class="cafe-name">Wu Lou Pie Pie 巫露派派</h3>
        <a href="https://food.suiis.com/res_img/700098412/commend/800065537.jpg">Wu Lou Pie Pie 巫露派派 菜單</a><br>
        <a href="https://www.google.com/maps?q=Wu+Lou+Pie+Pie+%E5%B7%AB%E9%9C%B2%E6%B4%BE%E6%B4%BE&source=lmns&bih=525&biw=1163&rlz=1C1AVFC_enTW937TW937&hl=zh-TW&sa=X&ved=2ahUKEwiV7Jnuzqb1AhUB6mEKHfUrCzMQ_AUoBHoECAEQBA">Wu Lou Pie Pie 巫露派派 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://images.zi.org.tw/ihappyday/2021/04/18233614/1618760173-ea40154339d6296c0b4b011889743801.jpg" alt="" width="380px" class="img-fluid">
        <h3 class="cafe-name">LOVELAND 專情島餐酒館</h3>
        <a href="https://scontent-tpe1-1.xx.fbcdn.net/v/t39.30808-6/236915432_378846200478284_2406275170401051401_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=c4c01c&_nc_ohc=dMXB_jIs7AsAX_1RsjQ&tn=XJpoH7ii5nELtaRN&_nc_ht=scontent-tpe1-1.xx&oh=00_AT9zsQWQC7a933E3d-2K1KW3w3kK9VdMPp_A72KZz3B4EQ&oe=61DFD8EE">LOVELAND 專情島餐酒館 菜單</a><br>
        <a href="https://www.google.com/maps?q=LOVELAND+%E5%B0%88%E6%83%85%E5%B3%B6%E9%A4%90%E9%85%92%E9%A4%A8&rlz=1C1AVFC_enTW937TW937&um=1&ie=UTF-8&sa=X&ved=2ahUKEwi3gYKN0Kb1AhUKyYsBHWD7AN0Q_AUoAXoECAIQAw">LOVELAND 專情島餐酒館 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://taitung.fun-taiwan.com/Images/PlayNotes/43028-G20140527040254.jpg" alt="" width="350px" class="img-fluid">
        <h3 class="cafe-name">麵包與巧克力倉庫</h3>
        <a href="https://img.paulyear.com/pixnet/469ae78e31a06edbb63f33ac66ab4a1a.jpg">麵包與巧克力倉庫 菜單</a><br>
        <a href="https://www.google.com/maps/place/%E9%BA%B5%E5%8C%85%E8%88%87%E5%B7%A7%E5%85%8B%E5%8A%9B%E5%80%89%E5%BA%AB/@22.9287759,121.2681509,17z/data=!3m1!4b1!4m5!3m4!1s0x346f9f5955555555:0xf528bafa5a4e211f!8m2!3d22.9287759!4d121.2703396?q=%E9%BA%B5%E5%8C%85%E8%88%87%E5%B7%A7%E5%85%8B%E5%8A%9B%E5%80%89%E5%BA%AB&rlz=1C5CHFA_enTW898TW899&biw=1280&bih=612&sxsrf=AOaemvIkWwTCi16jDWt2ZFcY41oPYgCi6Q:1641798110307&gs_lcp=Cgdnd3Mtd2l6EAEYADILCC4QgAQQxwEQrwEyBQgAEIAEMgQIABAeMgQIABAeMgYIABAFEB4yBggAEAUQHjoECAAQRzoHCCMQ6gIQJ0oECEEYAEoECEYYAFCUBlizV2CBX2gAcAF4AIABjAGIAYACkgEDMi4xmAEAoAEBoAECsAEKyAEKwAEB&um=1&ie=UTF-8&sa=X&ved=2ahUKEwjmo9z5zqb1AhXOdd4KHbsuAgcQ_AUoAXoECAEQAw&shorturl=1">麵包與巧克力倉庫 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://pic.pimg.tw/salzburgbnb/1510993206-3078880331.jpg" alt="" width="300px" class="img-fluid">
        <h3 class="cafe-name">丸山和食</h3>
        <a href="https://kuokuo.tw/wp-content/uploads/pixnet/1c0a8cd7120f30d10573598500d8b0d1.jpg">丸山和食 菜單</a><br>
        <a href="https://www.google.com/maps/place/%E4%B8%B8%E5%B1%B1%E5%92%8C%E9%A3%9F/@23.9061974,121.5296786,17z/data=!3m1!4b1!4m5!3m4!1s0x3468a3e0d1cb50f5:0x67e7753c877a087!8m2!3d23.9061977!4d121.5318666?shorturl=1">丸山和食 店面位置</a><br>
    </div>
</div>
{% endblock %}

apply/templates/apply/mid.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-sm-6 col-md-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWTZi3-RkK9TDMV5u-oNpzLz-gBvJ0sPtG-Q&usqp=CAU" alt="" width="350px" class="img-fluid">
        <h3 class="cafe-name">小次男咖哩所</h3>
        <a href="https://pic.pimg.tw/d0169953/1550923399-2719489492_wn.jpg">小次男咖哩所 菜單</a><br>
        <a href="https://www.google.com/maps/place/%E5%B0%8F%E6%AC%A1%E7%94%B7+%E5%92%96%E5%93%A9%E6%89%80/@24.1410804,120.6827946,15z/data=!4m2!3m1!1s0x0:0x14bd0c65c8fe11a?sa=X&ved=2ahUKEwj7n831xqb1AhVYH7kGHYqxA1oQ_BJ6BAguEAU">小次男咖哩所 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://lh3.googleusercontent.com/YnI7JeG09XAmtgNZlz2z1C4vHGiudB9i9D8ynhnwnnyyuOGJ8gTen4yR3e0diSqOTPrpJ5ho0LpoUSFkoegY3fD8ED7vJCBVzsvwyvyusn6EdA=s600" alt="" width="230px" class="img-fluid">
        <h3 class="cafe-name">空也素麵食</h3>
        <a href="https://scontent-tpe1-1.xx.fbcdn.net/v/t1.6435-9/120281124_3308683275845114_8384878911114048966_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=0debeb&_nc_ohc=WRUZvJ3FiNkAX8Zp4ar&_nc_ht=scontent-tpe1-1.xx&oh=00_AT-WtnMfaIw6FQbmrdXOX-vyPlu2UtZYUXq4F2pEh2TCjQ&oe=61FFB426">空也素麵食 菜單</a><br>
        <a href="https://www.google.com/maps/place/%E7%A9%BA%E4%B9%9F%E7%B4%A0%E9%BA%B5%E9%A3%9F/@24.1636558,120.6327641,17z/data=!3m1!4b1!4m5!3m4!1s0x34693d8de6c6c3ed:0x8bec7ec3e4202703!8m2!3d24.1636689!4d120.6349201?hl=zh-TW">空也素麵食 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0A4GiyZbe_LLrTLG3qytJIIPQ_ZieEcM3Jg&usqp=CAU" alt="" width="350px" class="img-fluid">
        <h3 class="cafe-name">鹽與胡椒餐館</h3>
        <a href="https://www.facebook.com/saltpeppertaiwan/menu">鹽與胡椒餐館 菜單</a><br>
        <a href="https://www.google.com/maps?bih=525&biw=1163&rlz=1C1AVFC_enTW937TW937&hl=zh-TW&uact=5&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgsILhCABBDHARCvATIFCAAQgAQyCwguEIAEEMcBEK8BMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIABBHELADOgQIABAeOgYIABAFEB5KBAhBGABKBAhGGABQqgdYuQhgmgpoAXAAeACAATuIAXOSAQEymAEAoAEByAEKwAEB&q=%E9%B9%BD%E8%88%87%E8%83%A1%E6%A4%92&um=1&ie=UTF-8&sa=X&ved=2ahUKEwjM17-_y6b1AhXfw4sBHapZA7sQ_AUoAXoECAIQAw">鹽與胡椒餐館 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWtHG8Pmha6NeqNbGoeQOEIYfIRf74F0BD2g&usqp=CAU" alt="" width="400px" class="img-fluid">
        <h3 class="cafe-name">禾壤餐酒館 SOIL RESTAURANT</h3>
        <a href="https://www.soil.com.tw/menu.html">禾壤餐酒館 SOIL RESTAURANT 菜單</a><br>
        <a href="https://www.google.com/maps?q=%E7%A6%BE%E5%A3%A4+soil&bih=525&biw=1148&rlz=1C1AVFC_enTW937TW937&hl=zh-TW&um=1&ie=UTF-8&sa=X&ved=2ahUKEwjhquGszKb1AhVBHKYKHcwAC8AQ_AUoAXoECAIQAw">禾壤餐酒館 SOIL RESTAURANT 店面位置</a><br>
    </div>
</div>
{% endblock %}

apply/templates/apply/my_apply.html
{% extends "base.html" %}

{% block content %}

<p>我的帳號</p>

{% if person %}
<ul>
    <li> 帳號: {{ user.username }}
    <li> mail: {{ person.ssn }}
    <li> Tel: {{ person.tel }}
    <li> 申請: {{ person.voucher_id }}
</ul>    
{% else %}
<p> 尚未綁定 </p>
{% endif %}

{% endblock %}

apply/templates/apply/north.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-sm-6 col-md-6">
        <img src="https://cdn2.ettoday.net/images/5206/d5206430.jpg" alt="" width="350px" class="img-fluid">
        <h3 class="cafe-name">Vegan Amore 蔬慕</h3>
        <a href="https://www.gooddeedstw.com/pages/veganamoremenu">Vegan Amore 蔬慕 菜單</a><br>
        <a href="https://www.google.com/maps/place/Vegan+Amore%E8%94%AC%E6%85%95/@25.0489918,121.515667,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a9c8e139ba2d:0x832846680e863c4b!8m2!3d25.0489918!4d121.5178557">Vegan Amore 蔬慕 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmdj5LaMPrt8e6DEdg_R8W8VdPt3X-FVWnRg&usqp=CAU" alt="" width="380px" class="img-fluid">
        <h3 class="cafe-name">odd fish cafe</h3>
        <a href="https://www.google.com/search?q=oddfish+%E8%8F%9C%E5%96%AE&rlz=1C1AVFC_enTW937TW937&source=lnms&tbm=isch&sa=X&ved=2ahUKEwio_MbGwab1AhVyIqYKHeShA1EQ_AUoAnoECAIQBA&biw=1163&bih=525&dpr=1.65">odd fish cafe 菜單</a><br>
        <a href="https://www.google.com/maps?q=oddfish&source=lmns&bih=525&biw=1163&rlz=1C1AVFC_enTW937TW937&hl=zh-TW&sa=X&ved=2ahUKEwjXu8ajwab1AhXI-WEKHZsSBFgQ_AUoAXoECAEQAQ">odd fish cafe 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrRdYo0SI8kO36EQqp4cOlC6S9vW_9C6Qmuw&usqp=CAU" alt="" width="350px" class="img-fluid">
        <h3 class="cafe-name">Mianto 艾果豐</h3>
        <a href="https://www.mianto.com.tw/html/menu.php">Mianto 艾果豐 菜單</a><br>
        <a href="https://www.google.com/maps?q=mianto+%E8%89%BE%E6%9E%9C%E8%B1%90&source=lmns&bih=525&biw=1163&rlz=1C1AVFC_enTW937TW937&hl=zh-TW&sa=X&ved=2ahUKEwjWrYq3wqb1AhUhE3AKHWWxCiMQ_AUoAXoECAEQAQ">Mianto 艾果豐 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSijSROhFA4Y8_8Vun3Jz5WhT9fpzkiLV9ckw&usqp=CAU" alt="" width="400px" class="img-fluid">
        <h3 class="cafe-name">TAMED FOX XINYI</h3>
        <a href="https://scontent-tpe1-1.xx.fbcdn.net/v/t1.6435-9/49103509_2034554656631950_7537579364376903680_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=730e14&_nc_ohc=UrwwNQxPe8wAX97KcAr&_nc_ht=scontent-tpe1-1.xx&oh=00_AT-qpvU_bmcf1iM7FuJKyXOhqF4A6r6gQImGWS1ojmo_fw&oe=6201F3BE">TAMED FOX XINYI 菜單</a><br>
        <a href="https://www.google.com/maps/place/TAMED+FOX+XINYI/@25.0369923,121.5671604,17z/data=!3m1!4b1!4m5!3m4!1s0x3442aba3de2ab327:0xa714062955bba236!8m2!3d25.0369875!4d121.5693491?hl=zh-TW">TAMED FOX XINYI 店面位置</a><br>
    </div>
</div>
{% endblock %}

apply/templates/apply/show_all.html
{% extends "base.html" %}

{% block content %}

<h3>目前的綁定狀況</h3>

   <table class="table table-striped">
        <thead>
            <tr>
                <th>身分證</th>
                <th>電話</th>
                <th>綁定模式</th>
            </tr>
        </thead>
        <tbody>
            {% for p in person_list %}
            <tr>
                <td>{{ p.ssn }}</td>
                <td>{{ p.tel }}</td>
                <td>{{ p.get_voucher_id_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
   </table>

{% endblock %}

apply/templates/apply/south.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-sm-6 col-md-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdCG_op2lU2e2Le4PlQFXF1d-VyNqRq9efMg&usqp=CAU" alt="" width="350px" class="img-fluid">
        <h3 class="cafe-name">老蔡牛肉</h3>
        <a href="https://lh3.googleusercontent.com/MTux4l68eg4fnlfs7juPbkEa6RmMeL3hlfh3LCZxwvg9YX-pmG9WcX_Jx_sRYp0-nlIEfhud7NdMk_vsbDSEMwC-YhP678Q=s600">老蔡牛肉 菜單</a><br>
        <a href="https://www.google.com/maps/place/%E8%80%81%E8%94%A1%E7%89%9B%E8%82%89/@22.6228309,120.2939673,17z/data=!3m1!4b1!4m5!3m4!1s0x346e047e099ad005:0x582b526755df58b1!8m2!3d22.622826!4d120.296156?hl=zh-TW">老蔡牛肉 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://aniseblog.tw/wp-content/uploads/2021/04/1619286860-8dff3e803fc4f42661712f3aa563abb1.jpg" alt="" width="380px" class="img-fluid">
        <h3 class="cafe-name">湖東牛肉</h3>
        <a href="https://pic.pimg.tw/kellyku/1569072386-231829784_wn.jpg">湖東牛肉 菜單</a><br>
        <a href="https://www.google.com/maps/place/%E6%B9%96%E6%9D%B1%E7%89%9B%E8%82%89%E9%A4%A8/@22.8777683,120.2496542,17z/data=!3m1!4b1!4m5!3m4!1s0x346e0cb69a78e703:0xc886b48f76386424!8m2!3d22.8777814!4d120.251879?hl=zh-TW">湖東牛肉 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://www.daisyyohoho.com/wp-content/uploads/2021/03/deepblue-27.jpg" alt="" width="380px" class="img-fluid">
        <h3 class="cafe-name">深藍咖啡館</h3>
        <a href="https://pic.pimg.tw/lintzuyang79/1522747103-637583560_wn.jpg">深藍咖啡館 菜單</a><br>
        <a href="https://www.google.com/maps/search/%E6%B7%B1%E8%97%8D%E5%92%96%E5%95%A1%E9%A4%A8+%E6%97%97%E8%89%A6/@22.9882541,120.183238,14z/data=!3m1!4b1">深藍咖啡館 店面位置</a><br>
    </div>

    <div class="col-sm-6 col-md-6">
        <img src="https://img.ltn.com.tw/Upload/playing/page/2021/02/05/210205-24559-3-UPdVq.jpg" alt="" width="400px" class="img-fluid">
        <h3 class="cafe-name">Wom salone</h3>
        <a href="https://www.google.com/search?q=wom+salone%E8%8F%9C%E5%96%AE&tbm=isch&ved=2ahUKEwjC5Jai1Kb1AhWJQfUHHbVMB5oQ2-cCegQIABAA&oq=wom+salone%E8%8F%9C%E5%96%AE&gs_lcp=CgNpbWcQAzIECAAQGDoFCAAQgARQzhtYnS1gzjJoAHAAeACAAWSIAaMDkgEDNy4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=1t_bYcKhOomD1e8PtZmd0Ak&bih=525&biw=1163&rlz=1C1AVFC_enTW937TW937">Wom salone 菜單</a><br>
        <a href="https://www.google.com/maps/place/Wom+salone/@22.9874375,120.1853573,17z/data=!3m1!4b1!4m5!3m4!1s0x346e77703a3eb859:0xa30fb72f5cab8048!8m2!3d22.9874021!4d120.1875429?hl=zh-TW">Wom salone 店面位置</a><br>
    </div>
</div>
{% endblock %}

apply/templates/apply/update_apply.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="form-group col-md-6">

                {{ form.as_p }}

                <input class="btn btn-success" type="submit" value="update" />
            </div>
        </div>
    </form>

{% endblock %}